Initialization
WildCodeSchool/lille-0919-js-projet2-runner pull request #2
Opened 2019-10-17 15:41 UTC by Lezarman-wcs

pull request for reset

2019-10-17 15:50 UTC, Adwarf14 submitted a review, later dismissed
Initialization ok

2019-10-18 05:45 UTC, LoicBrassart requested changes
## Blocking
- A file name should not have a capital letter, unless explicit contrary instructions! Please rename `Reset.css` to `reset.css`

## Good Ideas
- You have a Reset CSS named `reset.css` (if you omit the capital letter anyway)

2019-10-18 07:48 UTC, val-fcn approved these changes

2019-10-18 14:27 UTC, LoicBrassart approved these changes
Ok!

2019-10-18 14:55 UTC, merged