Header
WildCodeSchool/lille-0919-js-projet2-runner pull request #3
Opened 2019-10-18 15:43 UTC by HarleyBurton

Header.jsx
Header.scss
banner.png (dans public)

2019-10-18 15:48 UTC, LeoDiduch submitted a review, later dismissed

2019-10-19 07:43 UTC, LoicBrassart requested changes
## Blocking 
- Header.jsx: No need for the brackets around the file name. They're needed for everything _except_ strings

2019-10-20 16:42 UTC, LeoDiduch submitted a review, later dismissed

2019-10-22 06:34 UTC, LoicBrassart submitted a review, later dismissed
Ok!

2019-10-22 09:54 UTC, LeoDiduch submitted a review, later dismissed

2019-10-22 13:12 UTC, LeoDiduch approved these changes

2019-10-23 12:52 UTC, LoicBrassart approved these changes
Ok!
(But please refrain from adding new code to an already-reviewed PR, it brings a bit of confusion)

2019-10-23 15:38 UTC, merged