Contact page to dev PR
WildCodeSchool/lille-0919-js-projet2-runner pull request #6
Opened 2019-10-21 14:53 UTC by Lezarman-wcs

2019-10-22 13:39 UTC, val-fcn submitted a review, later dismissed

2019-10-23 13:27 UTC, Adwarf14 submitted a review, later dismissed

2019-10-24 14:53 UTC, LoicBrassart requested changes

2019-10-24 14:53 UTC, LoicBrassart commented on frontend/src/components/Contact.jsx
> +    // Value allocation displayed basic ********
These comments don't seem mandatory to me, they don't *explain* the code below, they merely describe it

2019-10-24 14:53 UTC, LoicBrassart commented on frontend/src/components/Contact.jsx
> +    this.state = { select: "object" };
I really don't like this. Do a single assignation to `this.state`

2019-10-24 15:01 UTC, Adwarf14 submitted a review, later dismissed

2019-10-24 15:21 UTC, LoicBrassart submitted a review, later dismissed
Ok

2019-10-25 15:45 UTC, Adwarf14 approved these changes

2019-10-28 08:33 UTC, merged