Leaderboard_page
WildCodeSchool/lille-0919-js-projet2-runner pull request #7
Opened 2019-10-22 13:10 UTC by Lezarman-wcs

2019-10-22 13:42 UTC, val-fcn submitted a review, later dismissed

2019-10-22 15:37 UTC, val-fcn submitted a review, later dismissed

2019-10-22 15:54 UTC, Adwarf14 submitted a review, later dismissed

2019-10-23 12:56 UTC, LoicBrassart requested changes
A little structure problem in this PR, but nothing too harsh I think ;-)

2019-10-23 12:56 UTC, LoicBrassart commented on frontend/src/components/LeaderBoard.jsx
> +    <div className="leaderBoard">
I think it'd be better to use *one* `<ol>` tag and to split the data in two in it (ex: flexbox)
The idea is, it'll be easier to fill these data when you use a real-world API

2019-10-28 09:37 UTC, LoicBrassart requested changes
Some things to change

2019-10-28 16:53 UTC, Adwarf14 submitted a review, later dismissed

2019-10-29 14:52 UTC, BlandineM approved these changes

2019-10-29 15:56 UTC, LoicBrassart reviewed
There's something I didn't understand, please explain it to me

2019-10-29 15:56 UTC, LoicBrassart commented on frontend/src/components/LeaderBoard.scss
> +      counter-reset: my-awesome-counter;
... Wat ?

2019-10-30 18:13 UTC, LoicBrassart approved these changes
Ok!

2019-10-31 01:58 UTC, merged