Jump feature
WildCodeSchool/lille-0919-js-projet2-runner pull request #8
Opened 2019-10-25 15:05 UTC by Adwarf14

Fonction jump du character, définition de la map (soumise à changement) plus les scss associés

2019-10-25 15:40 UTC, LeoDiduch submitted a review, later dismissed
That's good

2019-10-28 16:52 UTC, LeoDiduch submitted a review, later dismissed
It's all good

2019-10-29 07:38 UTC, LoicBrassart requested changes
Some things to change

2019-10-29 07:38 UTC, LoicBrassart commented on frontend/src/components/Map.scss
> +  z-index: 1;
Why this `z-index` ?

2019-10-29 07:38 UTC, LoicBrassart commented on frontend/src/components/Character.jsx
> +class Character extends React.Component {
If this component has no internal logic, please use a functional one instead

2019-10-29 07:38 UTC, LoicBrassart commented on frontend/src/components/Game.jsx
> +class Game extends React.Component {
If this component has no internal logic, please use a functional one instead

2019-10-29 07:38 UTC, LoicBrassart commented on frontend/src/components/Map.jsx
> +    if (keyCode === 32) {
Use `key === Space` instead, it's more readable

2019-10-29 07:38 UTC, LoicBrassart commented on frontend/src/components/Map.jsx
> +  carte = [
What purpose have the `0`s ?

2019-10-31 00:26 UTC, LoicBrassart approved these changes
SnE

2019-10-31 01:57 UTC, LeoDiduch approved these changes

2019-11-04 08:20 UTC, merged